dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.7"
matrix:
  include:
    - python: "3.7"
      env: TOXENV=flake8
addons:
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11
      - postgresql-server-dev-11
install: "pip install tox-travis"
script: tox
