dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.7"
matrix:
  include:
    - python: "3.7"
      env: TOXENV=flake8
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
      - postgresql-server-dev-10
install: "pip install tox-travis"
script: tox
