dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.7"
matrix:
  include:
    - python: "3.7"
      env: TOXENV=flake8
    - python: "3.7"
      env: TOXENV=docs
before_install:
  # don't install postgresql for flake8 and docs environments
  - if test -z "$TOXENV"; then sudo apt-get -y install --no-install-recommends postgresql-11 postgresql-client-11 postgresql-server-dev-11; fi
install: "pip install tox-travis"
script: tox
